# Generated by Django 4.0.6 on 2022-07-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
